[zh-cn]
  weight = 1
  # 网站语言, 仅在这里 CN 大写
  languageCode = "zh-CN"
  # 语言名称
  languageName = "简体中文"
  # 是否包括中日韩文字
  hasCJKLanguage = true
  # 默认每页列表显示的文章数目
  paginate = 12
  # [UA-XXXXXXXX-X] 谷歌分析代号 (被 params.analytics.google 替代)
  googleAnalytics = "G-4KZJV9VXTV"
  # 版权描述，仅仅用于 SEO
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  # 菜单配置
  [zh-cn.menu]
    [[zh-cn.menu.main]]
      identifier = "posts"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      name = "所有文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
  [zh-cn.params]
    # 网站描述
    description = "阿江的电子小屋"
    # 网站关键词
    keywords = ["Notion", "效率"]
    # 应用图标配置
    [zh-cn.params.app]
      # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
      title = "阿江小屋"
      # 是否隐藏网站图标资源链接
      noFavicon = false
      # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
      svgFavicon = ""
      # Safari 图标颜色
      iconColor = "#5bbad5"
      # Windows v8-10 磁贴颜色
      tileColor = "#da532c"
    # 搜索配置
    [zh-cn.params.search]
      enable = true
      # 搜索引擎的类型 ("lunr", "algolia", "fuse")
      type = "algolia"
      # 文章内容最长索引长度
      contentLength = 4000
      # 搜索框的占位提示语
      placeholder = ""
      # 最大结果数目
      maxResultLength = 10
      # 结果内容片段长度
      snippetLength = 50
      # 搜索结果中高亮部分的 HTML 标签
      highlightTag = "em"
      # 是否在搜索索引中使用基于 baseURL 的绝对路径
      absoluteURL = false
      [zh-cn.params.search.algolia]
        index = "zh_cn_index"
        appID = "5YGRNRQK1G"
        searchKey = "0ff6874805de24b84aa1d5ebccad56cd"
      [zh-cn.params.search.fuse]
        # https://fusejs.io/api/options.html
        isCaseSensitive = false
        minMatchCharLength = 2
        findAllMatches = false
        location = 0
        threshold = 0.1
        distance = 100
        ignoreLocation = true
        useExtendedSearch = false
        ignoreFieldNorm = false
    # 主页信息设置
    [zh-cn.params.home]
      # RSS 文章数目
      rss = 10
      # 主页个人信息
      [zh-cn.params.home.profile]
        enable = true
        # Gravatar 邮箱，用于优先在主页显示的头像
        gravatarEmail = ""
        # 主页显示头像的 URL
        avatarURL = "/avatar.png"
        # 主页显示的网站标题 (支持 HTML 格式)
        title = "阿江小屋"
        # 主页显示的网站副标题
        subtitle = "阿江的电子小屋"
        # 是否为副标题显示打字机动画
        typeit = true
        # 是否显示社交账号
        social = true
        # 免责声明 (支持 HTML 格式)
        disclaimer = ""
      # 主页文章列表
      [zh-cn.params.home.posts]
        enable = true
        # 主页每页显示文章数量
        paginate = 7
    # 主页的社交信息设置
    [zh-cn.params.social]
      GitHub = ""
      Linkedin = ""
      Twitter = ""
      Instagram = ""
      Facebook = ""
      Telegram = ""
      Medium = ""
      Gitlab = ""
      Youtubelegacy = ""
      Youtubecustom = ""
      Youtubechannel = ""
      Tumblr = ""
      Quora = ""
      Keybase = ""
      Pinterest = ""
      Reddit = ""
      Codepen = ""
      FreeCodeCamp = ""
      Bitbucket = ""
      Stackoverflow = ""
      Weibo = "5123346486"
      Odnoklassniki = ""
      VK = ""
      Flickr = ""
      Xing = ""
      Snapchat = ""
      Soundcloud = ""
      Spotify = ""
      Bandcamp = ""
      Paypal = ""
      Fivehundredpx = ""
      Mix = ""
      Goodreads = ""
      Lastfm = ""
      Foursquare = ""
      Hackernews = ""
      Kickstarter = ""
      Patreon = ""
      Steam = ""
      Twitch = ""
      Strava = ""
      Skype = ""
      Whatsapp = ""
      Zhihu = ""
      Douban = "175861330"
      Angellist = ""
      Slidershare = ""
      Jsfiddle = ""
      Deviantart = ""
      Behance = ""
      Dribbble = ""
      Wordpress = ""
      Vine = ""
      Googlescholar = ""
      Researchgate = ""
      Mastodon = ""
      Thingiverse = ""
      Devto = ""
      Gitea = ""
      XMPP = ""
      Matrix = ""
      Bilibili = "38486980"
      ORCID = ""
      Liberapay = ""
      Ko-Fi = ""
      BuyMeACoffee = ""
      Linktree = ""
      QQ = "2506395258"
      QQGroup = ""
      Email = "2506395258@qq.com"
      RSS = true
      # 赞助设置
    [zh-cn.params.sponsor]
      enable = false
      bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
      link = "https://mp.weixin.qq.com/s/2tFCchUD7TEhvn0Y1aoygw"
      # custom = "<a href=\"https://article.biliimg.com/bfs/article/1a8e85fa9edec8a0f965cdd8a60a7db97f6f6029.jpg" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"


